/**
 * Localnet bootstrap:
 *  - creates a mock wBTC SPL mint owned by a freshly generated "dev faucet" keypair
 *  - writes apps/web/.env.local with DEV_MODE flags + mint address + faucet secret
 *
 * Idempotent: if apps/web/.env.local already has VITE_WBTC_MINT and that mint
 * exists on the running validator, we leave everything in place.
 */
import {
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
} from "@solana/web3.js";
import { createMint } from "@solana/spl-token";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const RPC = "http://127.0.0.1:8899";
const DECIMALS = 8;
const ENV_PATH = "apps/web/.env.local";

function parseEnv(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of text.split("\n")) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m) out[m[1]!] = m[2]!;
  }
  return out;
}

async function main() {
  const conn = new Connection(RPC, "confirmed");

  // Verify validator is up.
  try {
    await conn.getVersion();
  } catch {
    console.error("✗ Cannot reach localnet at", RPC);
    console.error("  Start it first with `bun run localnet`.");
    process.exit(1);
  }

  // Default Solana CLI keypair — used to fund the dev faucet.
  const keypairPath = join(homedir(), ".config/solana/id.json");
  if (!existsSync(keypairPath)) {
    console.error("✗ No keypair at", keypairPath);
    console.error("  Run `solana-keygen new` first.");
    process.exit(1);
  }
  const cliKp = Keypair.fromSecretKey(
    Uint8Array.from(JSON.parse(readFileSync(keypairPath, "utf8"))),
  );

  // Fund the CLI keypair (localnet airdrop is unlimited).
  if ((await conn.getBalance(cliKp.publicKey)) < 10 * LAMPORTS_PER_SOL) {
    const sig = await conn.requestAirdrop(cliKp.publicKey, 100 * LAMPORTS_PER_SOL);
    await conn.confirmTransaction(sig, "confirmed");
  }

  // Reuse existing setup if the .env.local mint still resolves on this validator.
  if (existsSync(ENV_PATH)) {
    const prev = parseEnv(readFileSync(ENV_PATH, "utf8"));
    if (prev.VITE_WBTC_MINT && prev.VITE_DEV_FAUCET_SECRET) {
      try {
        const info = await conn.getAccountInfo(new PublicKey(prev.VITE_WBTC_MINT));
        if (info) {
          console.log("✓ Reusing existing mock wBTC mint:", prev.VITE_WBTC_MINT);
          return;
        }
      } catch {
        // fall through and recreate
      }
    }
  }

  // Generate the dev faucet keypair (mint authority).
  const faucet = Keypair.generate();
  const sig = await conn.requestAirdrop(faucet.publicKey, 5 * LAMPORTS_PER_SOL);
  await conn.confirmTransaction(sig, "confirmed");

  // Create the mock wBTC mint.
  const mint = await createMint(
    conn,
    faucet,                 // payer
    faucet.publicKey,       // mint authority
    null,                   // freeze authority
    DECIMALS,
  );

  const faucetHex = Buffer.from(faucet.secretKey).toString("hex");

  const lines = [
    "# Auto-generated by scripts/setup-localnet.ts — safe to delete.",
    "VITE_DEV_MODE=true",
    "VITE_RPC_URL=http://127.0.0.1:8899",
    "VITE_CLUSTER=localnet",
    `VITE_WBTC_MINT=${mint.toBase58()}`,
    `VITE_DEV_FAUCET_SECRET=${faucetHex}`,
    "",
  ];
  writeFileSync(ENV_PATH, lines.join("\n"));

  console.log("✓ Mock wBTC mint:        ", mint.toBase58());
  console.log("✓ Dev faucet authority:  ", faucet.publicKey.toBase58());
  console.log("✓ Wrote", ENV_PATH);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
